algoritmo "Area da parede"

var

altura, largura, area: real

inicio

    escreva("Me dê a alura da parede: ")
    leia(altura)
    escreval("Me dê a largura da parede: ")
    leia(largura)
    escreval("")
    area <- altura * largura
    escreval("Se a sua parede tem ", altura, " metros de altura e ", largura, " metros de largura, a área da sua parede é: ", area, " metros quadrados.")

fimalgoritmo